# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [0]:
import numpy as np

#### Create an array of 10 zeros 

In [0]:
#Name: Shreyans Jain
#Registration number: 21BCE6131

import numpy as np

zerosArray = np.zeros(10)

print(zeroArray)


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Create an array of 10 ones

In [0]:
import numpy as np

onesArray = np.ones(10)

print(ones_array)


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array of 10 fives

In [0]:
import numpy as np

fivesArray = 5 * np.ones(10)

print(fives_array)


array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Create an array of the integers from 10 to 50

In [0]:
import numpy as np

# Create an array of the integers from 10 to 50
arr = np.arange(10, 51)
print(arr)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [8]:
import numpy as np

# Create an array of even integers from 10 to 50
evenIntegersArray = np.arange(10, 51, 2)

print(evenIntegersArray)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
import numpy as np

# Create an array with values ranging from 0 to 8
values = np.arange(9)

# Reshape the array into a 3x3 matrix
sol = values.reshape(3, 3)

print(sol)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [4]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [5]:
import numpy as np

# Generate a random number between 0 and 1
random_number = np.random.rand()

print(random_number)


0.2817478608507864


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [6]:
import numpy as np

# Generate an array of 25 random numbers from a standard normal distribution
random_numbers = np.random.randn(25)

print(random_numbers)


[ 0.88636293 -1.17869199 -0.22169064 -0.58450545  0.79499321 -0.68874049
  0.25332173 -1.89504703  0.43663809  0.95766747 -0.18074969  0.24505868
  0.00786234 -0.58526209  0.14652018  0.14825553  1.45987858  0.01055774
  0.30526268  0.78019529  0.41984848 -2.24961957 -1.70936114  0.22319311
  1.08416573]


#### Create the following matrix:

In [7]:
import numpy as np

# Create an array of values from 0.01 to 1.00 with a step of 0.01
values = np.arange(0.01, 1.01, 0.01)

# Reshape the array into a 10x10 matrix
matrix = values.reshape(10, 10)

print(matrix)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [0]:
import numpy as np

# Create an array of 20 linearly spaced points between 0 and 1
points = np.linspace(0, 1, 20)

print(points)


array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [0]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [0]:
#Name: Shreyans Jain
#Registration number: 21BCE6131
import numpy as np

# Initialize the starting value
start_value = 12

# Initialize an empty list to store the rows
rows = []

# Generate the rows
for _ in range(3):
    row = np.arange(start_value, start_value + 4)
    rows.append(row)
    start_value = row[-1] + 2

# Create the array from the list of rows
output_array = np.array(rows)

print(output_array)


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [0]:
import numpy as np

# Create the matrix
matrix = np.array([[12, 13, 14, 15],
                   [17, 18, 19, 20],
                   [22, 23, 24, 25]])

# Access and print the number 20
number_20 = matrix[1, 3]
print(number_20)


20

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [0]:
import numpy as np

# Create the specified array
sol = np.array([[2], [7], [12]])

print(sol)


array([[ 2],
       [ 7],
       [12]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [1]:
import numpy as np

result_array = np.array([21, 22, 23, 24, 25])

print(result_array)


[21 22 23 24 25]


In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [0]:
import numpy as np

result_array = np.array([[16, 17, 18, 19, 20],
                         [21, 22, 23, 24, 25]])

print(result_array)


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [0]:
#Name: Shreyans Jain
#Registration number: 21BCE6131
import numpy as np

mat = np.array([[12, 13, 14, 15],
                [17, 18, 19, 20],
                [22, 23, 24, 25]])

# Calculate the sum of all values in the matrix
sum_of_values = np.sum(mat)

print(sum_of_values)


325

#### Get the standard deviation of the values in mat

In [0]:
import numpy as np

# Assuming you have the matrix called "mat"
mat = np.array([[12, 13, 14, 15],
                [17, 18, 19, 20],
                [22, 23, 24, 25]])

# Calculate the standard deviation of the values in the matrix
std_deviation = np.std(mat)

print(std_deviation)


7.2111025509279782

#### Get the sum of all the columns in mat

In [2]:
import numpy as np

# Assuming you have the matrix called "mat"
mat = np.array([[12, 13, 14, 15],
                [17, 18, 19, 20],
                [22, 23, 24, 25]])

# Calculate the sum of all columns in the matrix
sum_of_columns = np.sum(mat, axis=0)

print(sum_of_columns)


[51 54 57 60]
